container:
  image: "registry.gitlab.com/tigefa/ffmpeg"
  cpu: 8
  memory: 21

ffmpeg_task:
  timeout_in: 120m
  install_script:
    - apt-get update
    - apt-get dist-upgrade -yqq
    - apt-get install -yqq sudo lsb-base lsb-release apt-transport-https ca-certificates software-properties-common wget curl netcat aria2 whois figlet p7zip p7zip-full zip unzip
    - apt-get install -yqq wget aria2 ffmpeg telnet tree
  test_script:
    - aria2c --seed-time=1 --seed-ratio=1.0 "https://onejav.com/torrent/umso313/download/871724/onejav.com_umso313.torrent"
#    - "aria2c --header 'Host: nl31.seedr.cc' --user-agent 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:74.0) Gecko/20100101 Firefox/74.0' --header 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8' --header 'Accept-Language: id,en-US;q=0.7,en;q=0.3' --header 'Proxy-Authorization: Basic bzB6cThrZXItM3JnanVobTpmdTlhNzQ1aHp2' --referer 'https://www.seedr.cc/files/122723225' --header 'Upgrade-Insecure-Requests: 1' 'https://nl31.seedr.cc/ff_get/628702791/SSNI-752.mp4?st=BS-ORux2jUpj9cQm47MHmQ&e=1586458379' --out 'SSNI-752.mp4'"
    - ffmpeg -i "UMSO-313.mp4" -threads 16 -c:v libx265 -c:a copy -metadata title="UMSO 313" -preset veryfast -s 960x540 UMSO-313-x265.mp4
    - ls -hal
  binaries_artifacts:
    path: "UMSO-313-x265.mp4"
