container:
  image: "registry.gitlab.com/tigefa/ffmpeg"
  cpu: 8
  memory: 21

ffmpeg_task:
  timeout_in: 120m
  install_script:
    - apt-get update
    - apt-get dist-upgrade -yqq
    - apt-get install -yqq sudo lsb-base lsb-release apt-transport-https ca-certificates software-properties-common wget curl netcat aria2 whois figlet p7zip p7zip-full zip unzip
    - apt-get install -yqq wget aria2 ffmpeg telnet tree
  test_script:
    - aria2c --bt-seed-unverified=true --seed-time=1 --seed-ratio=1.0 "https://yts.mx/torrent/download/57F1662979CB4337A59A48F04AAD657E1F4AA9AA"
#    - "aria2c --header 'Host: nl32.seedr.cc' --user-agent 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:75.0) Gecko/20100101 Firefox/75.0' --header 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8' --header 'Accept-Language: id,en-US;q=0.7,en;q=0.3' --referer 'https://www.seedr.cc/files/125959815' --header 'Upgrade-Insecure-Requests: 1' 'https://nl32.seedr.cc/ff_get/644332729/Extraction.2020.720p.WEBRip.x264.AAC-[YTS.MX].mp4?st=mnu46s9_SeRpLO7QRl2tAQ&e=1588261042' --out 'Extraction.2020.720p.WEBRip.x264.AAC-[YTS.MX].mp4'"
    - ffmpeg -i "Namiya (2017) [BluRay] [720p] [YTS.LT]/Namiya.2017.720p.BluRay.x264-[YTS.LT].mp4" -threads 16 -c:v libx265 -c:a copy -metadata title="Namiya 2017" -preset veryfast Namiya.2017.720p.BluRay.x265.mp4
    - ls -hal
  binaries_artifacts:
    path: "Namiya.2017.720p.BluRay.x265.mp4"
